imports:
    - { resource: parameters.yml }

services:
    canonknipser.sug.controller:
        class: canonknipser\sug\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    canonknipser.sug.service:
        class: canonknipser\sug\service
        arguments:
            - '@user'
            - '%canonknipser.sug.tables.demo_table%'

    canonknipser.sug.listener:
        class: canonknipser\sug\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    canonknipser.sug.cron.task.demo:
        class: canonknipser\sug\cron\task\demo
        arguments:
            - '@config'
        calls:
            - [set_name, [cron.task.demo]]
        tags:
            - { name: cron.task }

    canonknipser.sug.notification.type.demo:
        class: canonknipser\sug\notification\type\demo
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
